export type { Operator, FindType, TextObjScope, VimState, CommandState, PersistentState, RecordedChange } from './types.js'
export { OPERATORS, SIMPLE_MOTIONS, FIND_KEYS, TEXT_OBJ_SCOPES, TEXT_OBJ_TYPES, MAX_VIM_COUNT, isOperatorKey, isTextObjScopeKey, createInitialVimState, createInitialPersistentState } from './types.js'
export type { Cursor } from './motions.js'
export { resolveMotion, isInclusiveMotion, isLinewiseMotion } from './motions.js'
export type { OperatorContext } from './operators.js'
export { executeOperatorMotion, executeOperatorFind, executeOperatorTextObj, executeLineOp, executeX, executeReplace, executeToggleCase, executeJoin, executePaste, executeIndent, executeOpenLine, executeOperatorG, executeOperatorGg } from './operators.js'
export type { TextObjectRange } from './textObjects.js'
export { findTextObject } from './textObjects.js'
export type { TransitionContext, TransitionResult } from './transitions.js'
export { transition } from './transitions.js'
