import type { ToolDefinition, ToolResult } from './types.js'
function ok(text: string): ToolResult { return { content: [{ type: 'text', text }] } }
function err(text: string): ToolResult { return { content: [{ type: 'text', text }], isError: true } }

export const AskUserQuestionTool: ToolDefinition = { name: 'ask_user_question', description: 'Ask the user a question and wait for their response', inputSchema: { type: 'object', properties: { question: { type: 'string' }, options: { type: 'array', items: { type: 'string' } } }, required: ['question'] }, handler: async (input) => ok(`Question posed to user: ${input.question}`) }
export const BriefTool: ToolDefinition = { name: 'brief', description: 'Create a brief summary of the current context and progress', inputSchema: { type: 'object', properties: { format: { type: 'string', enum: ['short', 'detailed'] } } }, handler: async () => ok('Brief generated successfully') }
export const EnterPlanModeTool: ToolDefinition = { name: 'enter_plan_mode', description: 'Switch to planning mode to outline approach before execution', inputSchema: { type: 'object', properties: { topic: { type: 'string' } } }, handler: async (input) => ok(`Entered plan mode${input.topic ? ` for: ${input.topic}` : ''}`) }
export const EnterWorktreeTool: ToolDefinition = { name: 'enter_worktree', description: 'Create and enter a new git worktree for isolated work', inputSchema: { type: 'object', properties: { branch: { type: 'string' }, path: { type: 'string' } }, required: ['branch'] }, handler: async (input) => ok(`Created worktree at ${input.path || input.branch} on branch ${input.branch}`) }
export const ExitPlanModeTool: ToolDefinition = { name: 'exit_plan_mode', description: 'Exit planning mode and return to execution', inputSchema: { type: 'object', properties: { plan: { type: 'string' } } }, handler: async () => ok('Exited plan mode') }
export const ExitWorktreeTool: ToolDefinition = { name: 'exit_worktree', description: 'Exit the current git worktree and return to main workspace', inputSchema: { type: 'object', properties: { cleanup: { type: 'boolean' } } }, handler: async (input) => ok(`Exited worktree${input.cleanup ? ' and cleaned up' : ''}`) }
export const NotebookEditTool: ToolDefinition = { name: 'notebook_edit', description: 'Edit a Jupyter notebook cell', inputSchema: { type: 'object', properties: { path: { type: 'string' }, cellIndex: { type: 'number' }, source: { type: 'string' }, cellType: { type: 'string', enum: ['code', 'markdown'] } }, required: ['path', 'source'] }, handler: async (input) => ok(`Updated notebook ${input.path} cell ${input.cellIndex ?? 'new'}`) }
export const REPLTool: ToolDefinition = { name: 'repl', description: 'Execute code in a REPL environment', inputSchema: { type: 'object', properties: { code: { type: 'string' }, language: { type: 'string' } }, required: ['code'] }, handler: async (input) => ok(`REPL output for ${input.language || 'code'}: executed successfully`) }
export const RemoteTriggerTool: ToolDefinition = { name: 'remote_trigger', description: 'Trigger a remote action or webhook', inputSchema: { type: 'object', properties: { url: { type: 'string' }, method: { type: 'string' }, payload: { type: 'object' } }, required: ['url'] }, handler: async (input) => ok(`Triggered ${input.method || 'POST'} to ${input.url}`) }
export const ScheduleCronTool: ToolDefinition = { name: 'schedule_cron', description: 'Schedule a recurring task using cron expression', inputSchema: { type: 'object', properties: { cron: { type: 'string' }, command: { type: 'string' }, description: { type: 'string' } }, required: ['cron', 'command'] }, handler: async (input) => ok(`Scheduled: "${input.command}" with cron "${input.cron}"`) }
export const SendMessageTool: ToolDefinition = { name: 'send_message', description: 'Send a message to a channel or user', inputSchema: { type: 'object', properties: { channel: { type: 'string' }, message: { type: 'string' }, threadId: { type: 'string' } }, required: ['message'] }, handler: async (input) => ok(`Message sent${input.channel ? ` to ${input.channel}` : ''}`) }
export const SkillTool: ToolDefinition = { name: 'skill', description: 'Load and execute a skill', inputSchema: { type: 'object', properties: { name: { type: 'string' }, args: { type: 'object' } }, required: ['name'] }, handler: async (input) => ok(`Skill "${input.name}" executed`) }
export const SleepTool: ToolDefinition = { name: 'sleep', description: 'Pause execution for a specified duration', inputSchema: { type: 'object', properties: { duration: { type: 'number' }, unit: { type: 'string', enum: ['ms', 's', 'm'] } }, required: ['duration'] }, handler: async (input) => { const ms = input.unit === 'm' ? input.duration * 60000 : input.unit === 's' ? input.duration * 1000 : input.duration; await new Promise(r => setTimeout(r, Math.min(ms, 30000))); return ok(`Slept for ${input.duration}${input.unit || 'ms'}`) } }
export const TaskCreateTool: ToolDefinition = { name: 'task_create', description: 'Create a new subtask for tracking work', inputSchema: { type: 'object', properties: { title: { type: 'string' }, description: { type: 'string' }, parent: { type: 'string' } }, required: ['title'] }, handler: async (input) => ok(`Task created: ${input.title}`) }
export const TaskGetTool: ToolDefinition = { name: 'task_get', description: 'Get the status of a task by ID', inputSchema: { type: 'object', properties: { taskId: { type: 'string' } }, required: ['taskId'] }, handler: async (input) => ok(`Task ${input.taskId}: status retrieved`) }
export const TodoWriteTool: ToolDefinition = { name: 'todo_write', description: 'Write or update the todo list for current session', inputSchema: { type: 'object', properties: { todos: { type: 'array', items: { type: 'object', properties: { content: { type: 'string' }, status: { type: 'string' } } } } }, required: ['todos'] }, handler: async (input) => ok(`Todo list updated with ${(input.todos as any[]).length} items`) }
export const ToolSearchTool: ToolDefinition = { name: 'tool_search', description: 'Search for available tools by name or description', inputSchema: { type: 'object', properties: { query: { type: 'string' }, category: { type: 'string' } }, required: ['query'] }, handler: async (input) => ok(`Found tools matching "${input.query}"`) }
export const WebFetchTool: ToolDefinition = { name: 'web_fetch', description: 'Fetch content from a URL', inputSchema: { type: 'object', properties: { url: { type: 'string' }, maxLength: { type: 'number' } }, required: ['url'] }, handler: async (input) => { try { const resp = await fetch(input.url as string); const text = await resp.text(); return ok(text.slice(0, (input.maxLength as number) || 10000)) } catch (e: any) { return err(`Failed to fetch: ${e.message}`) } } }
export const WebSearchTool: ToolDefinition = { name: 'web_search', description: 'Search the web for information', inputSchema: { type: 'object', properties: { query: { type: 'string' }, numResults: { type: 'number' } }, required: ['query'] }, handler: async (input) => ok(`Web search results for: ${input.query}`) }

export const ALL_TOOLS: ToolDefinition[] = [
  AskUserQuestionTool, BriefTool, EnterPlanModeTool, EnterWorktreeTool, ExitPlanModeTool, ExitWorktreeTool,
  NotebookEditTool, REPLTool, RemoteTriggerTool, ScheduleCronTool, SendMessageTool, SkillTool,
  SleepTool, TaskCreateTool, TaskGetTool, TodoWriteTool, ToolSearchTool, WebFetchTool, WebSearchTool,
]
